app = "spotify-utils"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "sqlite"
  destination = "/data"

[env]
  DB_FILE_NAME = "/data/sqlite.db"